// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/btc.proto

package btcAPI

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OutputRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Network              string   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	IsCoinBase           bool     `protobuf:"varint,3,opt,name=isCoinBase,proto3" json:"isCoinBase,omitempty"`
	IncludeUnused        bool     `protobuf:"varint,4,opt,name=includeUnused,proto3" json:"includeUnused,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputRequest) Reset()         { *m = OutputRequest{} }
func (m *OutputRequest) String() string { return proto.CompactTextString(m) }
func (*OutputRequest) ProtoMessage()    {}
func (*OutputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30be2f2b74974563, []int{0}
}

func (m *OutputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputRequest.Unmarshal(m, b)
}
func (m *OutputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputRequest.Marshal(b, m, deterministic)
}
func (m *OutputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputRequest.Merge(m, src)
}
func (m *OutputRequest) XXX_Size() int {
	return xxx_messageInfo_OutputRequest.Size(m)
}
func (m *OutputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OutputRequest proto.InternalMessageInfo

func (m *OutputRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *OutputRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *OutputRequest) GetIsCoinBase() bool {
	if m != nil {
		return m.IsCoinBase
	}
	return false
}

func (m *OutputRequest) GetIncludeUnused() bool {
	if m != nil {
		return m.IncludeUnused
	}
	return false
}

type BalanceJournalRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Network              string   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceJournalRequest) Reset()         { *m = BalanceJournalRequest{} }
func (m *BalanceJournalRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceJournalRequest) ProtoMessage()    {}
func (*BalanceJournalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30be2f2b74974563, []int{1}
}

func (m *BalanceJournalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceJournalRequest.Unmarshal(m, b)
}
func (m *BalanceJournalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceJournalRequest.Marshal(b, m, deterministic)
}
func (m *BalanceJournalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceJournalRequest.Merge(m, src)
}
func (m *BalanceJournalRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceJournalRequest.Size(m)
}
func (m *BalanceJournalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceJournalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceJournalRequest proto.InternalMessageInfo

func (m *BalanceJournalRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *BalanceJournalRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

type BalanceRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Network              string   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceRequest) Reset()         { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()    {}
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30be2f2b74974563, []int{2}
}

func (m *BalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest.Unmarshal(m, b)
}
func (m *BalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest.Marshal(b, m, deterministic)
}
func (m *BalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest.Merge(m, src)
}
func (m *BalanceRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest.Size(m)
}
func (m *BalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest proto.InternalMessageInfo

func (m *BalanceRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *BalanceRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

type BlockRequest struct {
	HashOrHeight         string   `protobuf:"bytes,1,opt,name=hash_or_height,json=hashOrHeight,proto3" json:"hash_or_height,omitempty"`
	Network              string   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30be2f2b74974563, []int{3}
}

func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (m *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(m, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

func (m *BlockRequest) GetHashOrHeight() string {
	if m != nil {
		return m.HashOrHeight
	}
	return ""
}

func (m *BlockRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

type TxRequest struct {
	TxID                 string   `protobuf:"bytes,1,opt,name=txID,proto3" json:"txID,omitempty"`
	Network              string   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxRequest) Reset()         { *m = TxRequest{} }
func (m *TxRequest) String() string { return proto.CompactTextString(m) }
func (*TxRequest) ProtoMessage()    {}
func (*TxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30be2f2b74974563, []int{4}
}

func (m *TxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxRequest.Unmarshal(m, b)
}
func (m *TxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxRequest.Marshal(b, m, deterministic)
}
func (m *TxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxRequest.Merge(m, src)
}
func (m *TxRequest) XXX_Size() int {
	return xxx_messageInfo_TxRequest.Size(m)
}
func (m *TxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxRequest proto.InternalMessageInfo

func (m *TxRequest) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

func (m *TxRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

type TxsRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Network              string   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxsRequest) Reset()         { *m = TxsRequest{} }
func (m *TxsRequest) String() string { return proto.CompactTextString(m) }
func (*TxsRequest) ProtoMessage()    {}
func (*TxsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30be2f2b74974563, []int{5}
}

func (m *TxsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxsRequest.Unmarshal(m, b)
}
func (m *TxsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxsRequest.Marshal(b, m, deterministic)
}
func (m *TxsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxsRequest.Merge(m, src)
}
func (m *TxsRequest) XXX_Size() int {
	return xxx_messageInfo_TxsRequest.Size(m)
}
func (m *TxsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxsRequest proto.InternalMessageInfo

func (m *TxsRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TxsRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

type RawResponse struct {
	RawBody              []byte   `protobuf:"bytes,1,opt,name=rawBody,proto3" json:"rawBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawResponse) Reset()         { *m = RawResponse{} }
func (m *RawResponse) String() string { return proto.CompactTextString(m) }
func (*RawResponse) ProtoMessage()    {}
func (*RawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_30be2f2b74974563, []int{6}
}

func (m *RawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawResponse.Unmarshal(m, b)
}
func (m *RawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawResponse.Marshal(b, m, deterministic)
}
func (m *RawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawResponse.Merge(m, src)
}
func (m *RawResponse) XXX_Size() int {
	return xxx_messageInfo_RawResponse.Size(m)
}
func (m *RawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawResponse proto.InternalMessageInfo

func (m *RawResponse) GetRawBody() []byte {
	if m != nil {
		return m.RawBody
	}
	return nil
}

func init() {
	proto.RegisterType((*OutputRequest)(nil), "btcAPI.OutputRequest")
	proto.RegisterType((*BalanceJournalRequest)(nil), "btcAPI.BalanceJournalRequest")
	proto.RegisterType((*BalanceRequest)(nil), "btcAPI.BalanceRequest")
	proto.RegisterType((*BlockRequest)(nil), "btcAPI.BlockRequest")
	proto.RegisterType((*TxRequest)(nil), "btcAPI.TxRequest")
	proto.RegisterType((*TxsRequest)(nil), "btcAPI.TxsRequest")
	proto.RegisterType((*RawResponse)(nil), "btcAPI.RawResponse")
}

func init() { proto.RegisterFile("api/proto/btc.proto", fileDescriptor_30be2f2b74974563) }

var fileDescriptor_30be2f2b74974563 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x51, 0x8b, 0xda, 0x40,
	0x10, 0xc7, 0x49, 0xb5, 0x56, 0xa7, 0x2a, 0xb8, 0xd6, 0x12, 0x0a, 0x2d, 0x22, 0x42, 0x7d, 0x52,
	0xda, 0xd2, 0x52, 0xdf, 0xda, 0x28, 0xa4, 0xb6, 0x50, 0x4b, 0x9a, 0x7b, 0x96, 0x35, 0x19, 0x2e,
	0xc1, 0x90, 0xcd, 0xed, 0x6e, 0xce, 0xdc, 0x47, 0xb8, 0x0f, 0x71, 0xdf, 0xf5, 0x70, 0xcd, 0xaa,
	0x39, 0x82, 0x70, 0xf8, 0x96, 0x9d, 0x99, 0xdf, 0x8f, 0xec, 0xf0, 0x5f, 0xe8, 0xd2, 0x24, 0x9c,
	0x24, 0x9c, 0x49, 0x36, 0x59, 0x4b, 0x6f, 0xac, 0xbe, 0x48, 0x6d, 0x2d, 0xbd, 0x9f, 0xff, 0x16,
	0x83, 0x7b, 0x03, 0x5a, 0xcb, 0x54, 0x26, 0xa9, 0x74, 0xf0, 0x26, 0x45, 0x21, 0x89, 0x09, 0xaf,
	0xa8, 0xef, 0x73, 0x14, 0xc2, 0x34, 0xfa, 0xc6, 0xa8, 0xe1, 0xe8, 0xe3, 0xae, 0x13, 0xa3, 0xdc,
	0x32, 0xbe, 0x31, 0x5f, 0xec, 0x3b, 0xf9, 0x91, 0x7c, 0x00, 0x08, 0xc5, 0x8c, 0x85, 0xb1, 0x45,
	0x05, 0x9a, 0x95, 0xbe, 0x31, 0xaa, 0x3b, 0x27, 0x15, 0x32, 0x84, 0x56, 0x18, 0x7b, 0x51, 0xea,
	0xe3, 0x55, 0x9c, 0x0a, 0xf4, 0xcd, 0xaa, 0x1a, 0x29, 0x16, 0x07, 0x7f, 0xa0, 0x67, 0xd1, 0x88,
	0xc6, 0x1e, 0xfe, 0x66, 0x29, 0x8f, 0x69, 0x74, 0xc1, 0x2f, 0x0d, 0xe6, 0xd0, 0xce, 0x65, 0x97,
	0x58, 0xfe, 0x42, 0xd3, 0x8a, 0x98, 0xb7, 0xd1, 0x8e, 0x21, 0xb4, 0x03, 0x2a, 0x82, 0x15, 0xe3,
	0xab, 0x00, 0xc3, 0xeb, 0x40, 0xe6, 0xaa, 0xe6, 0xae, 0xba, 0xe4, 0xbf, 0x54, 0xed, 0x8c, 0x6f,
	0x0a, 0x0d, 0x37, 0xd3, 0x32, 0x02, 0x55, 0x99, 0x2d, 0xe6, 0xb9, 0x42, 0x7d, 0x9f, 0x41, 0x7f,
	0x00, 0xb8, 0x99, 0xb8, 0xe4, 0x32, 0x1f, 0xe1, 0xb5, 0x43, 0xb7, 0x0e, 0x8a, 0x84, 0xc5, 0x02,
	0x77, 0x83, 0x9c, 0x6e, 0x2d, 0xe6, 0xdf, 0x29, 0x45, 0xd3, 0xd1, 0xc7, 0xcf, 0x0f, 0x15, 0x00,
	0xcb, 0x9d, 0xfd, 0x47, 0x7e, 0x1b, 0x7a, 0x48, 0xbe, 0x42, 0xdd, 0x46, 0xa9, 0xf6, 0x40, 0xde,
	0x8c, 0xf7, 0xc1, 0x19, 0x9f, 0xae, 0xe5, 0x5d, 0x57, 0x57, 0x4f, 0xfd, 0xdf, 0xa0, 0xa1, 0x31,
	0xf1, 0x1c, 0x6e, 0x02, 0x2f, 0x6d, 0x94, 0x6e, 0x46, 0x3a, 0xba, 0x7b, 0x58, 0x59, 0x39, 0xf0,
	0x09, 0x6a, 0x0a, 0x10, 0x84, 0x1c, 0x09, 0x71, 0x16, 0xf9, 0x0e, 0x60, 0xa3, 0xdc, 0x07, 0x5f,
	0x90, 0x9e, 0x1e, 0x29, 0xbc, 0x84, 0x72, 0x72, 0xaa, 0xc8, 0x3c, 0x5a, 0xe4, 0xed, 0xe1, 0x5a,
	0x85, 0xac, 0x95, 0xa3, 0x36, 0x74, 0x8e, 0x68, 0x1e, 0x71, 0xf2, 0xfe, 0x89, 0xa1, 0x18, 0xfd,
	0x52, 0xd1, 0xba, 0xa6, 0xde, 0xf0, 0x97, 0xc7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x8d, 0x05,
	0xf6, 0xda, 0x03, 0x00, 0x00,
}
